export {default as Home} from './Home'
export {default as About} from './About'
export {default as Contact} from './Contact'
export {default as Books} from './Books'
export {default as Ebooks} from './Ebooks'
export {default as BookDetails} from './BookDetails'
export {default as Ebook} from './Ebook'
export {default as Error} from './Error'